; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = Upload_UPDI

[env]
platform = atmelmegaavr
framework = arduino
board = ATtiny1614
board_build.f_cpu = 4000000L
board_hardware.oscillator = internal
build_flags = 
    -O2 -ffunction-sections
	-DSERIAL_RX_BUFFER_SIZE=128
	-DSERIAL_TX_BUFFER_SIZE=128
	-DPSITRACE=2
	-std=c++22
	-DCORE_ATTACH_OLD
    -Isrc/libz/PsiNetCred
    -Isrc/libz/PsiOutstation/src
    -Isrc/libz/PsiHAL/src
    -Isrc/libz/PsiIot/src
    -Isrc/libz/PsiCore/src
    -Isrc/libz/RFM69
	-Wl,--gc-sections,-Map,output.map 

	;-O2 -ffunction-sections ; -fdata-sections 
	;-Wl,--gc-sections,-Map,output.map ;,-u,vfprintf,-lprintf_flt ; full printf support
;,-u,vfprintf,-lprintf_flt ; full printf support
;-DCORE_ATTACH_ALL
;-DCORE_ATTACH_NONE

;-DRFM69_EXT_INTERRUPT

monitor_speed = 115200
lib_deps = 
lib_archive = no
build_src_filter = 
	+<*> 
	-<.git/> 
	-<.svn/>
	-<**/Kbd4017*.*>
	-<**/HS1101.*>
	-<**/RFM69_OTA.*>

[env:Upload_UPDI]
upload_protocol = serialupdi
upload_flags = 
upload_port = COM3
;lib_deps = 
;		lowpowerlab/SPIFlash@^101.1.3

[env:fuses]
upload_protocol = ${env:Upload_UPDI.upload_protocol}
upload_flags = ${env:Upload_UPDI.upload_flags}
upload_port = ${env:Upload_UPDI.upload_port}
;board_hardware.bod = 2.7v
board_hardware.bod = disabled
board_hardware.eesave = yes
; 16MHz
board_fuses.osccfg = 0x00
;lib_deps = lowpowerlab/SPIFlash@^101.1.3

;-----------------------------------------
; Burn it like this
;-----------------------------------------
; pio run --target fuses
;-----------------------------------------
